/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EjercicioProgra;

import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.Int;
import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class compraApp extends javax.swing.JFrame {
int t, j, c = 0, g = 0, p = 0,pago,total;
    /**
     * Creates new form ejercicio2
     */
    public compraApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txttelefono = new javax.swing.JFormattedTextField();
        txtfecha = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        chkPython = new javax.swing.JCheckBox();
        chkJava = new javax.swing.JCheckBox();
        chkC = new javax.swing.JCheckBox();
        chkGo = new javax.swing.JCheckBox();
        btnCalcula = new javax.swing.JButton();
        btnLimpia = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtcambio = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtpago = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtTotalPagar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("DATOS DEL CLIENTE");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(190, 10, 240, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Teléfono:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(70, 150, 80, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Fecha de inscripción:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 100, 140, 30);

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        jPanel2.add(txtnombre);
        txtnombre.setBounds(150, 50, 210, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Nombre:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(80, 50, 80, 30);

        try {
            txttelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(txttelefono);
        txttelefono.setBounds(150, 150, 140, 30);

        txtfecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        txtfecha.setToolTipText("ingresar dia/mes/año");
        txtfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfechaActionPerformed(evt);
            }
        });
        jPanel2.add(txtfecha);
        txtfecha.setBounds(150, 100, 210, 30);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(0, 190, 660, 30);

        chkPython.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        chkPython.setText("Python");
        chkPython.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkPythonItemStateChanged(evt);
            }
        });
        jPanel2.add(chkPython);
        chkPython.setBounds(30, 300, 90, 27);

        chkJava.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        chkJava.setText("Java");
        chkJava.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkJavaItemStateChanged(evt);
            }
        });
        chkJava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkJavaActionPerformed(evt);
            }
        });
        chkJava.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                chkJavaPropertyChange(evt);
            }
        });
        jPanel2.add(chkJava);
        chkJava.setBounds(30, 210, 140, 27);

        chkC.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        chkC.setText("C#");
        chkC.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkCItemStateChanged(evt);
            }
        });
        jPanel2.add(chkC);
        chkC.setBounds(30, 240, 140, 27);

        chkGo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        chkGo.setText("Go");
        chkGo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkGoItemStateChanged(evt);
            }
        });
        jPanel2.add(chkGo);
        chkGo.setBounds(30, 270, 140, 27);

        btnCalcula.setText("Calcular");
        btnCalcula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculaActionPerformed(evt);
            }
        });
        jPanel2.add(btnCalcula);
        btnCalcula.setBounds(150, 340, 71, 23);

        btnLimpia.setText("Limpiar");
        btnLimpia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiaActionPerformed(evt);
            }
        });
        jPanel2.add(btnLimpia);
        btnLimpia.setBounds(150, 310, 70, 23);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Cambio");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(270, 290, 80, 30);

        txtcambio.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtcambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcambioActionPerformed(evt);
            }
        });
        jPanel2.add(txtcambio);
        txtcambio.setBounds(360, 290, 170, 50);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Pago ");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(290, 210, 80, 30);

        txtpago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpagoActionPerformed(evt);
            }
        });
        jPanel2.add(txtpago);
        txtpago.setBounds(360, 210, 120, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Total a pagar");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(270, 250, 80, 30);

        txtTotalPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalPagarActionPerformed(evt);
            }
        });
        jPanel2.add(txtTotalPagar);
        txtTotalPagar.setBounds(360, 250, 120, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void btnCalculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculaActionPerformed
       // int t, j, c = 0, g = 0, p = 0;
        //java
        if(txtnombre.getText().isEmpty()||txtfecha.getText().isEmpty()||txttelefono.getText().isEmpty()||txtpago.getText().isEmpty())
        {
        JOptionPane.showMessageDialog(null,"Favor llene los valores");
        
        }     
        else 
        {
            //el campo tiene texto
             
        }
        
        
        
        
        
        
        if (chkJava.isSelected())
        j=200;
        else
        j=0;
        txtTotalPagar.setText(String.valueOf(j));
        t=j+c+g+p;
        txtTotalPagar.setText(String.valueOf(t));

        //C
        if(chkC.isSelected())
        c=300;
        else
        c=0;
        txtTotalPagar.setText(String.valueOf(c));
        t=j+c+g+p;
        txtTotalPagar.setText(String.valueOf(t));

        //Go
        if(chkGo.isSelected())
        g=250;
        else
        g=0;
        txtTotalPagar.setText(String.valueOf(g));
        t=j+c+g+p;
        txtTotalPagar.setText(String.valueOf(t));

        //Python
        if(chkPython.isSelected())
        p=250;
        else
        p=0;
        txtTotalPagar.setText(String.valueOf(p));
        t=j+c+g+p;
        txtTotalPagar.setText(String.valueOf(t));
        
        pago=parseInt(txtpago.getText());
        total = pago - t;
        txtcambio.setText(String.valueOf(total));

    }//GEN-LAST:event_btnCalculaActionPerformed

    private void txtcambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcambioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcambioActionPerformed

    private void txtpagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpagoActionPerformed

    private void txtTotalPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalPagarActionPerformed

    private void chkJavaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_chkJavaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_chkJavaPropertyChange

    private void chkJavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkJavaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkJavaActionPerformed

    private void chkJavaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkJavaItemStateChanged
        if (chkJava.isSelected())
        j=200;
        else
        j=0;
        txtTotalPagar.setText(String.valueOf(j));
        t=j+c+g+p;
        txtTotalPagar.setText(String.valueOf(t));
    }//GEN-LAST:event_chkJavaItemStateChanged

    private void chkGoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkGoItemStateChanged
         //Go
        if(chkGo.isSelected())
        g=250;
        else
        g=0;
        txtTotalPagar.setText(String.valueOf(g));
        t=j+c+g+p;
        txtTotalPagar.setText(String.valueOf(t));
    }//GEN-LAST:event_chkGoItemStateChanged

    private void chkCItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkCItemStateChanged
        if (chkC.isSelected())
        c=300;
        else
        c=0;
        txtTotalPagar.setText(String.valueOf(c));
        t=j+c+g+p;
        txtTotalPagar.setText(String.valueOf(t));
    }//GEN-LAST:event_chkCItemStateChanged

    private void chkPythonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkPythonItemStateChanged
        if (chkPython.isSelected())
        p=250;
        else
        p=0;
        txtTotalPagar.setText(String.valueOf(p));
        t=j+c+g+p;
        txtTotalPagar.setText(String.valueOf(t));
    }//GEN-LAST:event_chkPythonItemStateChanged

    private void btnLimpiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiaActionPerformed
      txtTotalPagar.setText("");
      txtpago.setText("");
      txtcambio.setText("");
      txtnombre.setText("");
      txtfecha.setText("");
      txttelefono.setText("");
      chkPython.setSelected(false);
      chkC.setSelected(false);
      chkGo.setSelected(false);
      chkJava.setSelected(false);
      
      
    }//GEN-LAST:event_btnLimpiaActionPerformed

    
    private void txtfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(compraApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(compraApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(compraApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(compraApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new compraApp().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcula;
    private javax.swing.JButton btnLimpia;
    private javax.swing.JCheckBox chkC;
    private javax.swing.JCheckBox chkGo;
    private javax.swing.JCheckBox chkJava;
    private javax.swing.JCheckBox chkPython;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtTotalPagar;
    private javax.swing.JTextField txtcambio;
    private javax.swing.JFormattedTextField txtfecha;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtpago;
    private javax.swing.JFormattedTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
